spring:
  application:
    name: Task-Management
  datasource:
    # url: jdbc:mysql://localhost:3306/task_tracker?createDatabaseIfNotExist=true <---- Add this line if you are not using docker mysql container
    url: ${SPRING_DATASOURCE_URL}  
    username: ${SPRING_DATASOURCE_USERNAME} #<---- Add username if you are not using docker mysql container
    password: ${SPRING_DATASOURCE_PASSWORD} #<---- Add password if you are not using docker mysql container
  
  
  config:
    import: optional:file:.env[.properties]
  jpa:
    show-sql: true

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900
    refreshTokenExpiration: 604800

