spring:
  application:
    name: Task-Management
  datasource:
    # url: jdbc:mysql://mysql-db:3306/task_tracker?createDatabaseIfNotExist=true
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  
  
  config:
    import: optional:file:.env[.properties]
  jpa:
    show-sql: true

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900
    refreshTokenExpiration: 604800

